name: CI and CD

on:
  push:
    branches:
      - main
      - develop
      # TODO:remove this branch before merge into develop
      - chore/setup
  pull_request:
    branches:
      - main
      - develop
      - 'chore/**'
      - 'feature/**'
      - 'release/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install node packages
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run unit test
        run: npm run test

      - name: Run end to end test
        run: npm run e2e
  
  deploy:
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_STAGING_APP: ${{ secrets.HEROKU_STAGING_APP }}
      HEROKU_PRODUCTION_APP: ${{ secrets.HEROKU_PRODUCTION_APP }}

    runs-on: ubuntu-latest

    needs: test

    steps:
      - uses: actions/checkout@v1

      - name: Deploy Production
        if: github.ref == 'refs/heads/main'
        run: |
          git remote add production https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PRODUCTION_APP.git
          git push -f production origin/main:refs/heads/master

      - name: Deploy Staging
        # TODO: change chore/setup-project to develop branch when chore branch merged
        if: github.ref == 'refs/heads/chore/setup-project'
        run: |
          git remote add staging https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_STAGING_APP.git
          git push -f staging origin/chore/setup-project:refs/heads/master

