# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
      - main
      - develop
      # TODO:remove this branch before merge into develop
      - chore/setup
  pull_request:
    branches:
      - main
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install node packages
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run unit test
        run: npm run test

      - name: Update webdriver
        run: ./node_modules/protractor/bin/webdriver-manager update

      - name: Run end to end test
        run: npm run e2e
